# TCL File Generated by Component Editor 8.1
# Sat Jun 06 01:24:31 CEST 2009
# DO NOT MODIFY


# +-----------------------------------
# | 
# | SdCardSlave "SdCardSlave" v1.0
# | null 2009.06.06.01:24:31
# | 
# | 
# | C:/dev/fpga/sdtest/SdCardSlave.v
# | 
# |    ./SdCardSlave.v syn, sim
# | 
# +-----------------------------------


# +-----------------------------------
# | module SdCardSlave
# | 
set_module_property NAME SdCardSlave
set_module_property VERSION 1.0
set_module_property GROUP ""
set_module_property DISPLAY_NAME SdCardSlave
set_module_property TOP_LEVEL_HDL_FILE SdCardSlave.v
set_module_property TOP_LEVEL_HDL_MODULE SdCardSlave
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
# | 
# +-----------------------------------

# +-----------------------------------
# | files
# | 
add_file SdCardSlave.v {SYNTHESIS SIMULATION}
# | 
# +-----------------------------------

# +-----------------------------------
# | parameters
# | 
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point clock_reset
# | 
add_interface clock_reset clock end
set_interface_property clock_reset ptfSchematicName ""

add_interface_port clock_reset clk clk Input 1
add_interface_port clock_reset reset reset Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point avalon_slave_0
# | 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressAlignment DYNAMIC
set_interface_property avalon_slave_0 addressSpan 32
set_interface_property avalon_slave_0 bridgesToMaster ""
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 isMemoryDevice false
set_interface_property avalon_slave_0 isNonVolatileStorage false
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 minimumUninterruptedRunLength 1
set_interface_property avalon_slave_0 printableDevice false
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0

set_interface_property avalon_slave_0 ASSOCIATED_CLOCK clock_reset

add_interface_port avalon_slave_0 address address Input 3
add_interface_port avalon_slave_0 read read Input 1
add_interface_port avalon_slave_0 write write Input 1
add_interface_port avalon_slave_0 writedata writedata Input 32
add_interface_port avalon_slave_0 readdata readdata Output 32
add_interface_port avalon_slave_0 begintransfer begintransfer Input 1
# | 
# +-----------------------------------

# +-----------------------------------
# | connection point conduit_end
# | 
add_interface conduit_end conduit end

set_interface_property conduit_end ASSOCIATED_CLOCK clock_reset

add_interface_port conduit_end SD_DAT3 export Bidir 1
add_interface_port conduit_end SD_DAT export Bidir 1
add_interface_port conduit_end SD_CMD export Bidir 1
add_interface_port conduit_end SD_CLK export Output 1
# | 
# +-----------------------------------
